### ISSUE TITLE
Installation in Docker

### ISSUE THREAD

**Issue by yogan** [DDP-Projekt/Installer#1]
Moin,

ich versuche aktuell, DDP in einem Docker-Image zu installieren. Aktuell sieht das `Dockerfile` in so aus:

```Dockerfile
FROM ubuntu:23.10

RUN apt-get update && apt-get install -y curl unzip build-essential locales

RUN cd /tmp && \
    curl -OL https://github.com/DDP-Projekt/Kompilierer/releases/latest/download/DDP-v0.0.1-alpha-linux-amd64.tar.gz && \
   tar -xzf ./DDP-v0.0.1-alpha-linux-amd64.tar.gz && \
   cd DDP-v0.0.1-alpha-linux-amd64 && \
   ./ddp-setup --force

# …
```

Das Setup scheint wohl etwas mit `make`/`gcc` zu bauen, das klappt auch erst mal ganz gut, aber ein `make clean` schlägt dann fehl:

```
root@a5ca7011a355:/tmp/DDP-v0.0.1-alpha-linux-amd64# ./ddp-setup
Welcome to the DDP Installer!
This setup will simply unpack some files and ask you for permission to change some environment variables and such.
Do you want to continue? [y/n]: y
installing german locales
/usr/sbin/locale-gen de_DE.UTF-8
Looking for gcc
[√] Found gcc in /usr/bin/gcc
Looking for make
[√] Found make in /usr/bin/make
/usr/bin/gcc -dumpfullversion
bin/kddp version --wortreich
local gcc version, and kddp gcc version mismatch (13.2.0 vs 11.4.0)
re-building runtime and stdlib
/usr/bin/make
[√] re-compiled the runtime
/usr/bin/make
[√] re-compiled the stdlib
removing pre-compiled runtime
removing pre-compiled lib/main.o lib/ddp_list_types_defs.o lib/ddp_list_types_defs.ll
removing pre-compiled stdlib
copying re-compiled runtime
copying re-compiled lib/main.o
regenerating lib/ddp_list_types_defs.ll and lib/ddp_list_types_defs.o
bin/kddp dump-list-defs -o lib/ddp_list_types_defs --llvm_ir --object
copying re-compiled stdlib
cleaning runtime directory
/usr/bin/make clean
[X] '/usr/bin/make clean ' failed (exit status 2) output: make: *** empty string invalid as file name.  Stop.

[!] error while cleaning runtime directory: exit status 2
cleaning stdlib directory
/usr/bin/make clean
[X] '/usr/bin/make clean ' failed (exit status 2) output: make: *** empty string invalid as file name.  Stop.

[!] error while cleaning stdlib directory: exit status 2
[√] recompiled libraries
Looking for code
[!] Unable to find code
Do you want to set the DDPPATH environment variable? [y/n]: y
Setting the environment variable DDPPATH to /tmp/DDP-v0.0.1-alpha-linux-amd64
Do you want to add the DDP/bin directory to your PATH? [y/n]: y
Appending /tmp/DDP-v0.0.1-alpha-linux-amd64/bin to the PATH
Press ENTER to exit...
```

Das ist die Ausgabe, die ich bekomme, wenn ich in dem Docker-Image selber noch mal ein `ddp-setup --force` ausführe.
Was mich etwas verwundert ist, dass da gar kein `Makefile` liegt. Ich sehe also auch nicht recht, wo das `make clean` herkommt und warum ihm da wohl ein Dateiname fehlt (`empty string invalid as file name`).

Irgendwelche Ideen?

**Comment by bafto** [comment]
Das ddp-setup compilet die runtime und stdlib nochmal für dein system neu, falls die gefundene GCC version anders ist als die, mit der DDP kompiliert wurde.

Die Makefiles dazu findest du in DDPInstallDir/lib/runtime und DDPInstallDir/lib/stdlib.
Das Setup versucht nach dem recompilen `make clean` aufzurufen, um die entstandenen .o Dateien zu löschen.

Das diese `make clean` fehlschlägt ist mir auch schon aufgefallen, ich habe mir das aber noch nicht genauer angesehen, da der Installer primär zum manuell installieren gedacht ist, und man solche Fehler dabei ignorieren kann.

Wahrscheinlich werde ich das `make clean` einfach entfernen, da die .o Dateien nicht so groß sind das es etwas ausmacht.

Für dein Dockerfile kannst du diesen Fehler einfach ignorieren.

Mir fällt auch grad auf, dass du ja trotz `--force` noch mit `Press Enter to exit...` gepromtet wirst, das ändere ich wohl auch noch.

**Comment by bafto** [comment]
Ich habs mir grad nochmal angeschaut, und mit dem letzten commit sollte jetzt beides gefixet sein.

Auf Windows übergebe ich ein `RM=ddp-rm` Argument zu `make clean`.
Auf Linux war das ein leerer string, und das hat make verwirrt.

Einfach das ddp-setup selber compilen wenn du den fix brauchst.
Ansonsten machen wir vielleicht in einer weilen noch einen Release mit ein paar Kleinigkeiten, da ist der fix dann auch im setup mit drin.

**Comment by yogan** [comment]
Danke, ich hatte gar nicht bemerkt, dass trotz des Fehlers der Build geklappt hat und die Binaries in `bin/` landen und funktionieren.
Dass das `--force` aktuell teilweise doch noch Eingaben erwartet, konnte ich mit `yes | ./ddp-setup --force` lösen.

Zu Dokumentationszwecken hier der Ausschnitt aus meinem `Dockerfile`, der so erst mal funktioniert:

```Dockerfile
RUN cd /usr/local/share/ && \
   curl -OL https://github.com/DDP-Projekt/Kompilierer/releases/latest/download/DDP-v0.0.1-alpha-linux-amd64.tar.gz && \
   tar -xzf ./DDP-v0.0.1-alpha-linux-amd64.tar.gz && \
   mv DDP-v0.0.1-alpha-linux-amd64 ddp && \
   cd ddp && \
   yes | ./ddp-setup --force
ENV PATH="/usr/local/share/ddp/bin:${PATH}"
ENV DDPPATH="/usr/local/share/ddp"
```
